### ISSUE TITLE
Widgets Stop Functioning Periodically

### ISSUE THREAD

**Issue by myntath** [eliotstocker/Light-Controller#28] opened 2015-02-18 02:11 UTC
I have noticed that from time to time the widgets stop working for me. I have widgets for both colour and white globes and sometimes they will be completely unresponsive, including hitting the settings and app buttons. When this happens the custom zone names I have set also disappear and are replaced with 'zone 1' etc... If the zone names are correct then the widget always functions reliably.

Opening the app normally and the exiting often fixes the problem but not always.

Any idea why this might be happening?

**Comment by mrwhale** [comment] 2015-02-18 02:54
Hey @myntath, I'm getting the same thing happening for me too! I thought it may have been because I am using my build that includes the android wear functionality, but obviously not. I'll hook my phone up to debug tonight to try find any errors its producing when that happens. I find it happens when I exit out of an app (Home button) to then use the widget, becomes totally unresponsive as myntath mentioned. Doesn't happen consistently though, sometimes works, sometimes doesn't. I'll try and find a way to reproduce the error too

**Comment by eliotstocker** [comment] 2015-02-18 08:27
Hmmm I was getting an NPE before sometimes on the widget, in solving that I think this may have happened I'm pretty sure it's when the widget needs to be Maya rusted and the widget host is null for some reason.

**Comment by eliotstocker** [comment] 2015-03-01 15:27
I do get this issue periodically but as of yet I'm not finding a way to consistently reproduce it, does anyone have steps to make it happen consistently? I'm pretty sure I know where the issue is in the code, but I'm not 100% on what causes it.

**Comment by eliotstocker** [comment] 2015-03-17 20:15
I believe this should now be sorted in the latest betas, can someone confirm?

**Comment by mrwhale** [comment] 2015-03-17 21:24
Yeah I haven't had any issues since beta 2, will try tonight once beta 3 has updated

**Comment by eliotstocker** [comment] 2015-03-18 15:19
for now i will close this, if anyone find the issue recuring in 1.7.0 beta 3+ let me know and we can reopen

**Closed by eliotstocker** 2015-03-18 15:19 UTC
Labels: bug
